[build]
  command = "pnpm run build"
  # DO NOT set publish to "."; Netlify handles it for Next.js

[[plugins]]
  package = "netlify-plugin-bundle-env"
  [plugins.inputs]
    directories = ["./"]
    include = ["NEXT_PUBLIC_*"]
    mask = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
